name: CI

on:
  pull_request:
    paths-ignore:
      - "*.markdown"
      - ".gitignore"
      - "LICENSE"
  push:
    branches:
      - "main"
    paths-ignore:
      - "*.markdown"
      - ".gitignore"
      - "LICENSE"
  
jobs:
  test:
    name: Run `dub test`
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run test
        run: dub test
